# criando a lista de gêneros, falta o numero 4
use bd_games;
INSERT INTO generos (nome, descricao) VALUES
('Ação', "Os jogos de ação são um gênero de videogame que enfatiza a habilidade do jogador em realizar ações rápidas e precisas. Esses jogos geralmente envolvem desafios que testam reflexos, coordenação e tempo de reação. Os jogadores frequentemente enfrentam inimigos ou obstáculos em cenários dinâmicos, onde a agilidade e a estratégia são cruciais para o sucesso. Os jogos de ação se destacam por suas mecânicas de jogo intensas e envolventes. Eles costumam incluir elementos como combate em tempo real, plataformas desafiadoras e a necessidade de coletar itens ou completar objetivos sob pressão. A narrativa pode ser secundária, mas muitos jogos de ação incorporam histórias cativantes que motivam o jogador a avançar. Dentro do gênero de ação, existem várias subcategorias, como jogos de tiro em primeira pessoa (FPS), jogos de plataforma e jogos de luta. Cada um desses tipos oferece experiências únicas, mas todos compartilham a necessidade de reflexos rápidos e decisões instantâneas."),
('Aventura', 'Os jogos de aventura são um gênero de videogame que se concentra na exploração, narrativa e resolução de quebra-cabeças. Nesses jogos, os jogadores assumem o papel de um personagem principal que deve interagir com personagens, coletar itens e resolver enigmas para progredir na história. A narrativa é uma das principais características, com histórias complexas e personagens memoráveis que incentivam a interação do jogador. Os jogos de aventura podem incluir elementos de exploração, diálogos interativos e escolhas que influenciam o desenrolar da trama. Exemplos famosos incluem "Monkey Island", "Grim Fandango" e "Life is Strange".'),
('Terror', "Os jogos de terror são uma categoria de jogos eletrônicos que têm como objetivo provocar medo, tensão e suspense nos jogadores. Eles frequentemente exploram elementos sobrenaturais, psicológicos e de sobrevivência, criando uma atmosfera envolvente que desafia os limites da coragem dos jogadores. Os jogos de terror podem incluir ambientes sombrios, trilhas sonoras inquietantes e narrativas envolventes, além de mecânicas de sobrevivência onde os jogadores devem gerenciar recursos limitados. Existem diversos subgêneros, como survival horror, que foca na sobrevivência em ambientes hostis, e terror psicológico, que explora os medos internos dos personagens."),
('Estratégia', "Os jogos de estratégia são um gênero de entretenimento que exige planejamento e tomada de decisões táticas para alcançar um objetivo específico. Eles podem ser encontrados em diversas plataformas, incluindo consoles, computadores e dispositivos móveis, e abrangem uma variedade de gêneros, como jogos de tabuleiro, jogos de guerra e jogos de simulação. Os jogos de estratégia podem ser classificados em várias categorias, incluindo jogos de estratégia em tempo real (RTS), jogos de estratégia por turnos (TBS) e jogos de estratégia baseados em cartas. Cada tipo oferece uma experiência única, onde os jogadores devem adaptar suas táticas e estratégias de acordo com as regras e dinâmicas específicas do jogo."),
('RPG', "Um RPG (Role-Playing Game) é um gênero de jogo eletrônico onde os jogadores assumem o papel de personagens fictícios e interagem em um mundo imaginário. Os RPGs se destacam pela narrativa imersiva, interação social e a capacidade de moldar a história de forma colaborativa. Existem diferentes tipos de RPGs, como RPG de mesa, RPG de computador e RPG online, cada um com suas próprias mecânicas e estilos de jogo."),
('Esporte', "Os video games, especificamente os que simulam esportes, são considerados um gênero esportivo por várias razões. Eles simula a prática de esportes, incluindo a competição entre jogadores ou equipes. Esses jogos podem ser competitivos, como os que simulam futebol, eixando em estratégias e habilidades físicas, ou podem ser mais focados em ação e estratégia, como os que simulam corridas ou batalhas. A competição entre jogadores ou equipes em video games é uma característica distintiva do gênero, que é frequentemente comparado a esportes tradicionais."),
('Corrida', "Os jogos de corrida são um gênero de videogame que simula competições automobilísticas, onde os jogadores controlam veículos em pistas diversas, com o objetivo de completar uma corrida no menor tempo possível. Esses jogos podem variar desde simulações realistas até experiências arcade, oferecendo uma ampla gama de estilos de jogo e mecânicas. A popularidade dos jogos de corrida se deve à adrenalina proporcionada pelas corridas e à possibilidade de competir contra amigos ou jogadores de todo o mundo."),
('Tabuleiro', "Os jogos de tabuleiro são uma proposta de entretenimento que normalmente envolve um tabuleiro e complementos como dados, cartas ou fichas. Os participantes devem seguir uma série de regras e instruções para alcançar um objetivo e obter a vitória. Esses jogos podem exigir habilidades intelectuais, como estratégia e memória, ou podem depender do acaso."),
('Puzzle', "Os jogos de quebra-cabeça são um gênero de jogos eletrônicos que desafiam a lógica e a estratégia dos jogadores. Eles envolvem a resolução de quebra-cabeças e enigmas, testando habilidades como lógica, raciocínio e reconhecimento de padrões. Existem diversos tipos de jogos de quebra-cabeça, incluindo quebra-cabeças clássicos, jogos de combinação de cores, jogos de palavras e jogos de lógica. Esses jogos são populares por oferecer uma experiência única e desafiadora, além de proporcionar benefícios cognitivos, como melhoramento da memória e concentração."),
('Luta', "Um jogo de luta é um gênero de videogame que se concentra em combates entre personagens, geralmente em um ambiente bidimensional ou tridimensional. Esses jogos são caracterizados por sua jogabilidade intensa, onde os jogadores controlam lutadores que utilizam uma variedade de movimentos, combos e técnicas especiais para derrotar seus oponentes. O objetivo principal é reduzir a barra de vida do adversário a zero, utilizando habilidades estratégicas e reflexos rápidos."),
('Musical', "A música de jogos eletrônicos, também conhecida como trilha sonora de videogames, é um elemento fundamental que complementa a experiência do jogador. Desde os primeiros jogos eletrônicos, a música tem desempenhado um papel crucial em criar atmosferas, evocar emoções e intensificar a narrativa. A evolução da tecnologia permitiu que as trilhas sonoras se tornassem cada vez mais sofisticadas, incorporando orquestrações complexas e efeitos sonoros imersivos. A música de jogos não é apenas um fundo sonoro; ela é uma ferramenta narrativa poderosa. Composições bem elaboradas podem guiar o jogador através de diferentes emoções, desde a tensão de uma batalha até a alegria de uma vitória. Além disso, a música ajuda a estabelecer a identidade de um jogo, tornando-se parte integrante da sua marca.");

